In [ ]:
import torch
print(torch.__version__)

2.9.0+cu126


# **Creating a Tensor**

In [ ]:
# create empty tensor
X = torch.empty(5,6)

In [ ]:
# check type
type(X)

torch.Tensor

In [ ]:
# create zeros tensor
torch.zeros(5,6)

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [ ]:
# create ones tensor
torch.ones([5,6])

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [ ]:
# create tensor with rand
torch.rand(5,6)

tensor([[0.1831, 0.5623, 0.4906, 0.5027, 0.2136, 0.9124],
        [0.6087, 0.5079, 0.2489, 0.9022, 0.8348, 0.0046],
        [0.3433, 0.3643, 0.4931, 0.0942, 0.1918, 0.1473],
        [0.3740, 0.1115, 0.2366, 0.8892, 0.0637, 0.3307],
        [0.8910, 0.0741, 0.5614, 0.7349, 0.7730, 0.8655]])

In [ ]:
# create tensor with rand using seed
torch.manual_seed(42)
torch.rand(5,6)

tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408, 0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739],
        [0.2666, 0.6274, 0.2696, 0.4414, 0.2969, 0.8317],
        [0.1053, 0.2695, 0.3588, 0.1994, 0.5472, 0.0062]])

In [ ]:
# create custom tensor
torch.tensor(((1,2),(3,4),(5,6)))

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
torch.tensor([[1,2],[3,4],[5,6]])

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
# create a tensor using arange
print(torch.arange(0,10))
print(torch.arange(0,10,2))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 2, 4, 6, 8])


In [ ]:
# create a tensor using linespace
torch.linspace(0,100,10)

tensor([  0.0000,  11.1111,  22.2222,  33.3333,  44.4444,  55.5556,  66.6667,
         77.7778,  88.8889, 100.0000])

In [ ]:
# create a tensor using eye
torch.eye(7)

tensor([[1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
# create a tensor using full
torch.full((5,6),6)

tensor([[6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6]])

# **Tensor Shapes**

In [ ]:
# find tensor shapes
a = torch.tensor(((1,2,3,0),(4,5,6,0),(7,8,9,0)))
a

tensor([[1, 2, 3, 0],
        [4, 5, 6, 0],
        [7, 8, 9, 0]])

In [ ]:
a.shape

torch.Size([3, 4])

In [ ]:
# create tensor of same shapes
print(f" Empty tensor of shape 'a'\n", (torch.empty_like(a)))
print(f" Zeros tensor of shape 'a'\n", (torch.zeros_like(a)))
print(f" Ones tensor of shape 'a'\n", (torch.ones_like(a)))
print(f" Random tensor of shape 'a'\n", torch.rand_like(a, dtype=torch.float32))


 Empty tensor of shape 'a'
 tensor([[                  0, 7310593858020254331, 3616445622929465956,
         6068653468538645814],
        [3761132630351427888, 6500164516308858926, 7309453675965983778,
         8315168162784306286],
        [8367752027310484831, 7954801838398993778, 2459029315949324647,
         3906422089127977571]])
 Zeros tensor of shape 'a'
 tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])
 Ones tensor of shape 'a'
 tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])
 Random tensor of shape 'a'
 tensor([[0.9516, 0.0753, 0.8860, 0.5832],
        [0.3376, 0.8090, 0.5779, 0.9040],
        [0.5547, 0.3423, 0.6343, 0.3644]])


# **Tensor Data Types**

In [ ]:
# find data type
a.dtype

torch.int64

In [ ]:
# assign data type
b = torch.tensor(((1,2,3,0),(4,5,6,0),(7,8,9,0)), dtype=torch.int64)
b

tensor([[1, 2, 3, 0],
        [4, 5, 6, 0],
        [7, 8, 9, 0]])

In [ ]:
# change data type
b.to(torch.float32)


tensor([[1., 2., 3., 0.],
        [4., 5., 6., 0.],
        [7., 8., 9., 0.]])

# **Mathematical operations**

## 1. Scalar operation

In [ ]:
x = torch.rand(2,2)
x

tensor([[0.7104, 0.9464],
        [0.7890, 0.2814]])

In [ ]:
print(f"Addition", x+2)
print(f"Substraction", x-2)
print(f"Multiplication", x*2)
print(f"Division", x/2)
print(f"Int Division", (x*100)//2)
print(f"Mod", ((x*100)//2)%2)
print(f"Power", x**2)

Addition tensor([[2.7104, 2.9464],
        [2.7890, 2.2814]])
Substraction tensor([[-1.2896, -1.0536],
        [-1.2110, -1.7186]])
Multiplication tensor([[1.4209, 1.8928],
        [1.5781, 0.5628]])
Division tensor([[0.3552, 0.4732],
        [0.3945, 0.1407]])
Int Division tensor([[35., 47.],
        [39., 14.]])
Mod tensor([[1., 1.],
        [1., 0.]])
Power tensor([[0.5047, 0.8957],
        [0.6226, 0.0792]])


## 2. Element wise operation

In [ ]:
a = torch.rand(4,3)
b = torch.rand(4,3)

print(a)
print(b)

tensor([[0.7886, 0.5895, 0.7539],
        [0.1952, 0.0050, 0.3068],
        [0.1165, 0.9103, 0.6440],
        [0.7071, 0.6581, 0.4913]])
tensor([[0.8913, 0.1447, 0.5315],
        [0.1587, 0.6542, 0.3278],
        [0.6532, 0.3958, 0.9147],
        [0.2036, 0.2018, 0.2018]])


In [ ]:
print(f"Addition", a+b)
print(f"Substraction", a-b)
print(f"Multiplication", a*b)
print(f"Division", a/b)
print(f"Int Division", a//b)
print(f"Mod", a%b)
print(f"Power", a**b)

Addition tensor([[1.6799, 0.7342, 1.2854],
        [0.3540, 0.6592, 0.6346],
        [0.7697, 1.3061, 1.5587],
        [0.9108, 0.8599, 0.6931]])
Substraction tensor([[-0.1027,  0.4447,  0.2224],
        [ 0.0365, -0.6491, -0.0210],
        [-0.5367,  0.5144, -0.2707],
        [ 0.5035,  0.4563,  0.2895]])
Multiplication tensor([[0.7029, 0.0853, 0.4007],
        [0.0310, 0.0033, 0.1006],
        [0.0761, 0.3603, 0.5891],
        [0.1440, 0.1328, 0.0991]])
Division tensor([[0.8848, 4.0725, 1.4185],
        [1.2301, 0.0077, 0.9360],
        [0.1783, 2.2997, 0.7041],
        [3.4722, 3.2613, 2.4348]])
Int Division tensor([[0., 4., 1.],
        [1., 0., 0.],
        [0., 2., 0.],
        [3., 3., 2.]])
Mod tensor([[0.7886, 0.0105, 0.2224],
        [0.0365, 0.0050, 0.3068],
        [0.1165, 0.1186, 0.6440],
        [0.0962, 0.0527, 0.0877]])
Power tensor([[0.8093, 0.9264, 0.8606],
        [0.7716, 0.0314, 0.6789],
        [0.2455, 0.9635, 0.6686],
        [0.9319, 0.9190, 0.8664]])


In [ ]:
c = torch.tensor([1, -2, 3, -4])
c

# absolute
print(f"Absolute",(torch.abs(c)))

# negative
print(f"Negative",(torch.neg(c)))

# round
print(f"Round",(torch.round(torch.tensor(3.315926))))
print(f"Round",(torch.round(torch.tensor(3.515926))))

# ceil
print(f"Ceil",(torch.ceil(torch.tensor(3.315926))))
print(f"Ceil",(torch.ceil(torch.tensor(3.515926))))

# floor
print(f"Floor",(torch.floor(torch.tensor(3.315926))))
print(f"Floor",(torch.floor(torch.tensor(3.515926))))

# clamp
print(f"Clamp",(torch.clamp(torch.tensor([[1.9, 2.3, 3.7, 4.4]]), min=2, max=3)))

Absolute tensor([1, 2, 3, 4])
Negative tensor([-1,  2, -3,  4])
Round tensor(3.)
Round tensor(4.)
Ceil tensor(4.)
Ceil tensor(4.)
Floor tensor(3.)
Floor tensor(3.)
Clamp tensor([[2.0000, 2.3000, 3.0000, 3.0000]])


## 3. Reduction operation

In [ ]:
d = torch.randint(0,100, (2,3), dtype=torch.float32)
d

tensor([[77., 89., 84.],
        [53., 48.,  9.]])

In [ ]:
print(f" Sum of d,", torch.sum(d))
print(f" Sum of along columns,", torch.sum(d, dim=0))
print(f" Sum of along rows,", torch.sum(d, dim=1))
print(f" Mean of d,", torch.mean(d))
print(f" Mean of d along columns,", torch.mean(d, dim=0))
print(f" Median of d,", torch.median(d))
print(f" Max of d,", torch.max(d))
print(f" Min of d,", torch.min(d))
print(f" Product of d,", torch.prod(d))
print(f" Standard Deviation of d,", torch.std(d))
print(f" Variance of d,", torch.var(d))
print(f" Index of largest number d,", torch.argmax(d))
print(f" Index of smallest number d,", torch.argmin(d))


 Sum of d, tensor(360.)
 Sum of along columns, tensor([130., 137.,  93.])
 Sum of along rows, tensor([250., 110.])
 Mean of d, tensor(60.)
 Mean of d along columns, tensor([65.0000, 68.5000, 46.5000])
 Median of d, tensor(53.)
 Max of d, tensor(89.)
 Min of d, tensor(9.)
 Product of d, tensor(1.3180e+10)
 Standard Deviation of d, tensor(30.)
 Variance of d, tensor(900.)
 Index of largest number d, tensor(1)
 Index of smallest number d, tensor(5)


## 4. Matrix operations

In [ ]:
e = torch.randint(0,10,(2,3))
f = torch.randint(0,10,(3,2))
print(e)
print(f)

tensor([[3, 7, 8],
        [1, 4, 1]])
tensor([[6, 3],
        [2, 0],
        [9, 8]])


In [ ]:
# matrix multiplication
torch.matmul(e,f)

tensor([[104,  73],
        [ 23,  11]])

In [ ]:
vector1 = torch.tensor([2,2])
vector2 = torch.tensor([3,4])
print(vector1)
print(vector2)

tensor([2, 2])
tensor([3, 4])


In [ ]:
# dot product
torch.dot(vector1, vector2)

tensor(14)

In [ ]:
# transpose
torch.manual_seed(42)
g = torch.randint(0,50,(5,6))
print(g)
torch.transpose(g, 0, 1)

tensor([[42, 17, 26, 14, 26, 35],
        [20, 24,  0, 13, 28, 14],
        [10,  4, 31, 22, 15, 45],
        [17,  6, 49, 26, 23, 11],
        [49, 13, 41, 19, 37, 19]])


tensor([[42, 20, 10, 17, 49],
        [17, 24,  4,  6, 13],
        [26,  0, 31, 49, 41],
        [14, 13, 22, 26, 19],
        [26, 28, 15, 23, 37],
        [35, 14, 45, 11, 19]])

In [ ]:
# determinant
torch.manual_seed(42)
h = torch.randint(0,5,(3,3), dtype=torch.float32)
print(h)
torch.det(h)

tensor([[2., 2., 1.],
        [4., 1., 0.],
        [0., 4., 0.]])


tensor(16.)

In [ ]:
# inversre
torch.inverse(h)

tensor([[ 0.0000,  0.2500, -0.0625],
        [ 0.0000,  0.0000,  0.2500],
        [ 1.0000, -0.5000, -0.3750]])

## 5. Comparison operations

In [ ]:
i = torch.randint(0,10,(2,3))
j = torch.randint(0,10,(2,3))
print(i)
print(j)

tensor([[3, 8, 4],
        [0, 4, 1]])
tensor([[2, 5, 5],
        [7, 6, 9]])


In [ ]:
print(f" Equal", torch.eq(i,j))
print(f" Not Equal", torch.ne(i,j))
print(f" Greater Than", torch.gt(i,j))
print(f" Less Than", torch.lt(i,j))
print(f" Greater Than or Equal", torch.ge(i,j))
print(f" Less Than or Equal", torch.ge(i,j))

 Equal tensor([[False, False, False],
        [False, False, False]])
 Not Equal tensor([[True, True, True],
        [True, True, True]])
 Greater Than tensor([[ True,  True, False],
        [False, False, False]])
 Less Than tensor([[False, False,  True],
        [ True,  True,  True]])
 Greater Than or Equal tensor([[ True,  True, False],
        [False, False, False]])
 Less Than or Equal tensor([[ True,  True, False],
        [False, False, False]])


## 6. Special functions

In [ ]:
k = torch.randint(0,10,(2,3), dtype=torch.float32)
k

tensor([[6., 3., 1.],
        [9., 3., 1.]])

In [ ]:
print(f" Log", torch.log(k))
print(f" Exponential", torch.exp(k))
print(f" Log10", torch.log10(k))
print(f" Log2", torch.log2(k))
print(f" Square Root", torch.sqrt(k))
print(f" Sine", torch.sin(k))
print(f" Cosine", torch.cos(k))
print(f" Tangent", torch.tan(k))
print(f" Sigmoid", torch.sigmoid(k))
print(f" Softmax", torch.softmax(k, dim =0))
print(f" Relu", torch.relu(k))

 Log tensor([[1.7918, 1.0986, 0.0000],
        [2.1972, 1.0986, 0.0000]])
 Exponential tensor([[4.0343e+02, 2.0086e+01, 2.7183e+00],
        [8.1031e+03, 2.0086e+01, 2.7183e+00]])
 Log10 tensor([[0.7782, 0.4771, 0.0000],
        [0.9542, 0.4771, 0.0000]])
 Log2 tensor([[2.5850, 1.5850, 0.0000],
        [3.1699, 1.5850, 0.0000]])
 Square Root tensor([[2.4495, 1.7321, 1.0000],
        [3.0000, 1.7321, 1.0000]])
 Sine tensor([[-0.2794,  0.1411,  0.8415],
        [ 0.4121,  0.1411,  0.8415]])
 Cosine tensor([[ 0.9602, -0.9900,  0.5403],
        [-0.9111, -0.9900,  0.5403]])
 Tangent tensor([[-0.2910, -0.1425,  1.5574],
        [-0.4523, -0.1425,  1.5574]])
 Sigmoid tensor([[0.9975, 0.9526, 0.7311],
        [0.9999, 0.9526, 0.7311]])
 Softmax tensor([[0.0474, 0.5000, 0.5000],
        [0.9526, 0.5000, 0.5000]])
 Relu tensor([[6., 3., 1.],
        [9., 3., 1.]])


# **Inplace Operations**

In [ ]:
m =  torch.rand(2,3)
n =  torch.rand(2,3)
print(m)
print(n)

tensor([[0.1994, 0.5472, 0.0062],
        [0.9516, 0.0753, 0.8860]])
tensor([[0.5832, 0.3376, 0.8090],
        [0.5779, 0.9040, 0.5547]])


In [ ]:
m+n

tensor([[0.7826, 0.8848, 0.8151],
        [1.5295, 0.9792, 1.4407]])

In [ ]:
m.add_(n)

tensor([[0.7826, 0.8848, 0.8151],
        [1.5295, 0.9792, 1.4407]])

In [ ]:
m

tensor([[0.7826, 0.8848, 0.8151],
        [1.5295, 0.9792, 1.4407]])

In [ ]:
n

tensor([[0.5832, 0.3376, 0.8090],
        [0.5779, 0.9040, 0.5547]])

In [ ]:
torch.relu(m)

tensor([[0.7826, 0.8848, 0.8151],
        [1.5295, 0.9792, 1.4407]])

In [ ]:
m.relu_()

tensor([[0.7826, 0.8848, 0.8151],
        [1.5295, 0.9792, 1.4407]])

In [ ]:
m

tensor([[0.7826, 0.8848, 0.8151],
        [1.5295, 0.9792, 1.4407]])

In [ ]:
m.sigmoid_()

tensor([[0.6862, 0.7078, 0.6932],
        [0.8219, 0.7270, 0.8086]])

# **Copying a Tensor**

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.3423, 0.6343, 0.3644],
        [0.7104, 0.9464, 0.7890]])

In [ ]:
b = a

In [ ]:
b

tensor([[0.3423, 0.6343, 0.3644],
        [0.7104, 0.9464, 0.7890]])

In [ ]:
a[0][0]=0

In [ ]:
a

tensor([[0.0000, 0.6343, 0.3644],
        [0.7104, 0.9464, 0.7890]])

In [ ]:
b

tensor([[0.0000, 0.6343, 0.3644],
        [0.7104, 0.9464, 0.7890]])

In [ ]:
id(a)

133305899259120

In [ ]:
id(b)

133305899259120

In [ ]:
b = a.clone()

In [ ]:
a

tensor([[0.0000, 0.6343, 0.3644],
        [0.7104, 0.9464, 0.7890]])

In [ ]:
a[0][0]=1.875

In [ ]:
a

tensor([[1.8750, 0.6343, 0.3644],
        [0.7104, 0.9464, 0.7890]])

In [ ]:
b

tensor([[0.0000, 0.6343, 0.3644],
        [0.7104, 0.9464, 0.7890]])

In [ ]:
id(a)

133305899259120

In [ ]:
id(b)

133305899580896

## **Tensor Operations on GPU**

In [ ]:
torch.cuda.is_available()

True

In [63]:
device = torch.device("cuda")

In [64]:
# create new tensor on gpu
k = torch.rand((2,3), device=device)
k

tensor([[0.6130, 0.0101, 0.3984],
        [0.0403, 0.1563, 0.4825]], device='cuda:0')

In [65]:
q = torch.rand((2,3))
q

tensor([[0.2814, 0.7886, 0.5895],
        [0.7539, 0.1952, 0.0050]])

In [67]:
w = q.to(device)
w

tensor([[0.2814, 0.7886, 0.5895],
        [0.7539, 0.1952, 0.0050]], device='cuda:0')

In [68]:
k+w

tensor([[0.8944, 0.7987, 0.9879],
        [0.7942, 0.3515, 0.4875]], device='cuda:0')

In [71]:
# gpu vs cpu
import torch
import time

device = torch.device("cuda")

# size of matrices
size = 10000

# create random matrices on cpu
matrix_cpu1 = torch.rand(size, size)
matrix_cpu2 = torch.rand(size, size)

# measure time on cpu
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)
cpu_time = time.time() - start_time

print(f"Time on CPU:{cpu_time:4f} seconds")

# move matrices to gpu
matrix_gpu1 = matrix_cpu1.to(device)
matrix_gpu2 = matrix_cpu2.to(device)

# measure time on gpu
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)
gpu_time = time.time() - start_time

print(f"Time on GPU:{gpu_time:4f} seconds")

# compare results
print("\nSpeedUp(CPU time/GPU time):", cpu_time/gpu_time)

Time on CPU:16.845551 seconds
Time on GPU:0.099327 seconds

SpeedUp(CPU time/GPU time): 169.59674562178355
