In [1]:
import torch
print(torch.__version__)

2.9.0+cpu


# **Creating a Tensor**

In [2]:
# create empty tensor
X = torch.empty(5,6)

In [3]:
# check type
type(X)

torch.Tensor

In [4]:
# create zeros tensor
torch.zeros(5,6)

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [5]:
# create ones tensor
torch.ones([5,6])

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [6]:
# create tensor with rand
torch.rand(5,6)

tensor([[0.8592, 0.1432, 0.2342, 0.0432, 0.0480, 0.9956],
        [0.5375, 0.9201, 0.0929, 0.2838, 0.1875, 0.3023],
        [0.1617, 0.6384, 0.7140, 0.1136, 0.9775, 0.4911],
        [0.9928, 0.7696, 0.7167, 0.6041, 0.1618, 0.1787],
        [0.5639, 0.3934, 0.3088, 0.8260, 0.1024, 0.1546]])

In [7]:
# create tensor with rand using seed
torch.manual_seed(42)
torch.rand(5,6)

tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408, 0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739],
        [0.2666, 0.6274, 0.2696, 0.4414, 0.2969, 0.8317],
        [0.1053, 0.2695, 0.3588, 0.1994, 0.5472, 0.0062]])

In [8]:
# create custom tensor
torch.tensor(((1,2),(3,4),(5,6)))

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [9]:
torch.tensor([[1,2],[3,4],[5,6]])

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [10]:
# create a tensor using arange
print(torch.arange(0,10))
print(torch.arange(0,10,2))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 2, 4, 6, 8])


In [11]:
# create a tensor using linespace
torch.linspace(0,100,10)

tensor([  0.0000,  11.1111,  22.2222,  33.3333,  44.4444,  55.5556,  66.6667,
         77.7778,  88.8889, 100.0000])

In [12]:
# create a tensor using eye
torch.eye(7)

tensor([[1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 1.]])

In [13]:
# create a tensor using full
torch.full((5,6),6)

tensor([[6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6]])

# **Tensor Shapes**

In [14]:
# find tensor shapes
a = torch.tensor(((1,2,3,0),(4,5,6,0),(7,8,9,0)))
a

tensor([[1, 2, 3, 0],
        [4, 5, 6, 0],
        [7, 8, 9, 0]])

In [15]:
a.shape

torch.Size([3, 4])

In [16]:
# create tensor of same shapes
print(f" Empty tensor of shape 'a'\n", (torch.empty_like(a)))
print(f" Zeros tensor of shape 'a'\n", (torch.zeros_like(a)))
print(f" Ones tensor of shape 'a'\n", (torch.ones_like(a)))
print(f" Random tensor of shape 'a'\n", torch.rand_like(a, dtype=torch.float32))


 Empty tensor of shape 'a'
 tensor([[131939890486736,       410757120,       412463584,       412478432],
        [              0,       410802336,       385908544, 131939317384048],
        [              0,               0,               0,               0]])
 Zeros tensor of shape 'a'
 tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])
 Ones tensor of shape 'a'
 tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])
 Random tensor of shape 'a'
 tensor([[0.9516, 0.0753, 0.8860, 0.5832],
        [0.3376, 0.8090, 0.5779, 0.9040],
        [0.5547, 0.3423, 0.6343, 0.3644]])


# **Tensor Data Types**

In [17]:
# find data type
a.dtype

torch.int64

In [18]:
# assign data type
b = torch.tensor(((1,2,3,0),(4,5,6,0),(7,8,9,0)), dtype=torch.int64)
b

tensor([[1, 2, 3, 0],
        [4, 5, 6, 0],
        [7, 8, 9, 0]])

In [19]:
# change data type
b.to(torch.float32)


tensor([[1., 2., 3., 0.],
        [4., 5., 6., 0.],
        [7., 8., 9., 0.]])

# **Mathematical operations**

## 1. Scalar operation

In [20]:
x = torch.rand(2,2)
x

tensor([[0.7104, 0.9464],
        [0.7890, 0.2814]])

In [21]:
print(f"Addition", x+2)
print(f"Substraction", x-2)
print(f"Multiplication", x*2)
print(f"Division", x/2)
print(f"Int Division", (x*100)//2)
print(f"Mod", ((x*100)//2)%2)
print(f"Power", x**2)

Addition tensor([[2.7104, 2.9464],
        [2.7890, 2.2814]])
Substraction tensor([[-1.2896, -1.0536],
        [-1.2110, -1.7186]])
Multiplication tensor([[1.4209, 1.8928],
        [1.5781, 0.5628]])
Division tensor([[0.3552, 0.4732],
        [0.3945, 0.1407]])
Int Division tensor([[35., 47.],
        [39., 14.]])
Mod tensor([[1., 1.],
        [1., 0.]])
Power tensor([[0.5047, 0.8957],
        [0.6226, 0.0792]])


## 2. Element wise operation

In [22]:
a = torch.rand(4,3)
b = torch.rand(4,3)

print(a)
print(b)

tensor([[0.7886, 0.5895, 0.7539],
        [0.1952, 0.0050, 0.3068],
        [0.1165, 0.9103, 0.6440],
        [0.7071, 0.6581, 0.4913]])
tensor([[0.8913, 0.1447, 0.5315],
        [0.1587, 0.6542, 0.3278],
        [0.6532, 0.3958, 0.9147],
        [0.2036, 0.2018, 0.2018]])


In [23]:
print(f"Addition", a+b)
print(f"Substraction", a-b)
print(f"Multiplication", a*b)
print(f"Division", a/b)
print(f"Int Division", a//b)
print(f"Mod", a%b)
print(f"Power", a**b)

Addition tensor([[1.6799, 0.7342, 1.2854],
        [0.3540, 0.6592, 0.6346],
        [0.7697, 1.3061, 1.5587],
        [0.9108, 0.8599, 0.6931]])
Substraction tensor([[-0.1027,  0.4447,  0.2224],
        [ 0.0365, -0.6491, -0.0210],
        [-0.5367,  0.5144, -0.2707],
        [ 0.5035,  0.4563,  0.2895]])
Multiplication tensor([[0.7029, 0.0853, 0.4007],
        [0.0310, 0.0033, 0.1006],
        [0.0761, 0.3603, 0.5891],
        [0.1440, 0.1328, 0.0991]])
Division tensor([[0.8848, 4.0725, 1.4185],
        [1.2301, 0.0077, 0.9360],
        [0.1783, 2.2997, 0.7041],
        [3.4722, 3.2613, 2.4348]])
Int Division tensor([[0., 4., 1.],
        [1., 0., 0.],
        [0., 2., 0.],
        [3., 3., 2.]])
Mod tensor([[0.7886, 0.0105, 0.2224],
        [0.0365, 0.0050, 0.3068],
        [0.1165, 0.1186, 0.6440],
        [0.0962, 0.0527, 0.0877]])
Power tensor([[0.8093, 0.9264, 0.8606],
        [0.7716, 0.0314, 0.6789],
        [0.2455, 0.9635, 0.6686],
        [0.9319, 0.9190, 0.8664]])


In [24]:
c = torch.tensor([1, -2, 3, -4])
c

# absolute
print(f"Absolute",(torch.abs(c)))

# negative
print(f"Negative",(torch.neg(c)))

# round
print(f"Round",(torch.round(torch.tensor(3.315926))))
print(f"Round",(torch.round(torch.tensor(3.515926))))

# ceil
print(f"Ceil",(torch.ceil(torch.tensor(3.315926))))
print(f"Ceil",(torch.ceil(torch.tensor(3.515926))))

# floor
print(f"Floor",(torch.floor(torch.tensor(3.315926))))
print(f"Floor",(torch.floor(torch.tensor(3.515926))))

# clamp
print(f"Clamp",(torch.clamp(torch.tensor([[1.9, 2.3, 3.7, 4.4]]), min=2, max=3)))

Absolute tensor([1, 2, 3, 4])
Negative tensor([-1,  2, -3,  4])
Round tensor(3.)
Round tensor(4.)
Ceil tensor(4.)
Ceil tensor(4.)
Floor tensor(3.)
Floor tensor(3.)
Clamp tensor([[2.0000, 2.3000, 3.0000, 3.0000]])


## 3. Reduction operation

In [25]:
d = torch.randint(0,100, (2,3), dtype=torch.float32)
d

tensor([[77., 89., 84.],
        [53., 48.,  9.]])

In [26]:
print(f" Sum of d,", torch.sum(d))
print(f" Sum of along columns,", torch.sum(d, dim=0))
print(f" Sum of along rows,", torch.sum(d, dim=1))
print(f" Mean of d,", torch.mean(d))
print(f" Mean of d along columns,", torch.mean(d, dim=0))
print(f" Median of d,", torch.median(d))
print(f" Max of d,", torch.max(d))
print(f" Min of d,", torch.min(d))
print(f" Product of d,", torch.prod(d))
print(f" Standard Deviation of d,", torch.std(d))
print(f" Variance of d,", torch.var(d))
print(f" Index of largest number d,", torch.argmax(d))
print(f" Index of smallest number d,", torch.argmin(d))


 Sum of d, tensor(360.)
 Sum of along columns, tensor([130., 137.,  93.])
 Sum of along rows, tensor([250., 110.])
 Mean of d, tensor(60.)
 Mean of d along columns, tensor([65.0000, 68.5000, 46.5000])
 Median of d, tensor(53.)
 Max of d, tensor(89.)
 Min of d, tensor(9.)
 Product of d, tensor(1.3180e+10)
 Standard Deviation of d, tensor(30.)
 Variance of d, tensor(900.)
 Index of largest number d, tensor(1)
 Index of smallest number d, tensor(5)


## 4. Matrix operations

In [27]:
e = torch.randint(0,10,(2,3))
f = torch.randint(0,10,(3,2))
print(e)
print(f)

tensor([[3, 7, 8],
        [1, 4, 1]])
tensor([[6, 3],
        [2, 0],
        [9, 8]])


In [28]:
# matrix multiplication
torch.matmul(e,f)

tensor([[104,  73],
        [ 23,  11]])

In [29]:
vector1 = torch.tensor([2,2])
vector2 = torch.tensor([3,4])
print(vector1)
print(vector2)

tensor([2, 2])
tensor([3, 4])


In [30]:
# dot product
torch.dot(vector1, vector2)

tensor(14)

In [31]:
# transpose
torch.manual_seed(42)
g = torch.randint(0,50,(5,6))
print(g)
torch.transpose(g, 0, 1)

tensor([[42, 17, 26, 14, 26, 35],
        [20, 24,  0, 13, 28, 14],
        [10,  4, 31, 22, 15, 45],
        [17,  6, 49, 26, 23, 11],
        [49, 13, 41, 19, 37, 19]])


tensor([[42, 20, 10, 17, 49],
        [17, 24,  4,  6, 13],
        [26,  0, 31, 49, 41],
        [14, 13, 22, 26, 19],
        [26, 28, 15, 23, 37],
        [35, 14, 45, 11, 19]])

In [32]:
# determinant
torch.manual_seed(42)
h = torch.randint(0,5,(3,3), dtype=torch.float32)
print(h)
torch.det(h)

tensor([[2., 2., 1.],
        [4., 1., 0.],
        [0., 4., 0.]])


tensor(16.)

In [33]:
# inversre
torch.inverse(h)

tensor([[ 0.0000,  0.2500, -0.0625],
        [ 0.0000,  0.0000,  0.2500],
        [ 1.0000, -0.5000, -0.3750]])

## 5. Comparison operations

In [34]:
i = torch.randint(0,10,(2,3))
j = torch.randint(0,10,(2,3))
print(i)
print(j)

tensor([[3, 8, 4],
        [0, 4, 1]])
tensor([[2, 5, 5],
        [7, 6, 9]])


In [35]:
print(f" Equal", torch.eq(i,j))
print(f" Not Equal", torch.ne(i,j))
print(f" Greater Than", torch.gt(i,j))
print(f" Less Than", torch.lt(i,j))
print(f" Greater Than or Equal", torch.ge(i,j))
print(f" Less Than or Equal", torch.ge(i,j))

 Equal tensor([[False, False, False],
        [False, False, False]])
 Not Equal tensor([[True, True, True],
        [True, True, True]])
 Greater Than tensor([[ True,  True, False],
        [False, False, False]])
 Less Than tensor([[False, False,  True],
        [ True,  True,  True]])
 Greater Than or Equal tensor([[ True,  True, False],
        [False, False, False]])
 Less Than or Equal tensor([[ True,  True, False],
        [False, False, False]])


## 6. Special functions

In [36]:
k = torch.randint(0,10,(2,3), dtype=torch.float32)
k

tensor([[6., 3., 1.],
        [9., 3., 1.]])

In [37]:
print(f" Log", torch.log(k))
print(f" Exponential", torch.exp(k))
print(f" Log10", torch.log10(k))
print(f" Log2", torch.log2(k))
print(f" Square Root", torch.sqrt(k))
print(f" Sine", torch.sin(k))
print(f" Cosine", torch.cos(k))
print(f" Tangent", torch.tan(k))
print(f" Sigmoid", torch.sigmoid(k))
print(f" Softmax", torch.softmax(k, dim =0))
print(f" Relu", torch.relu(k))

 Log tensor([[1.7918, 1.0986, 0.0000],
        [2.1972, 1.0986, 0.0000]])
 Exponential tensor([[4.0343e+02, 2.0086e+01, 2.7183e+00],
        [8.1031e+03, 2.0086e+01, 2.7183e+00]])
 Log10 tensor([[0.7782, 0.4771, 0.0000],
        [0.9542, 0.4771, 0.0000]])
 Log2 tensor([[2.5850, 1.5850, 0.0000],
        [3.1699, 1.5850, 0.0000]])
 Square Root tensor([[2.4495, 1.7321, 1.0000],
        [3.0000, 1.7321, 1.0000]])
 Sine tensor([[-0.2794,  0.1411,  0.8415],
        [ 0.4121,  0.1411,  0.8415]])
 Cosine tensor([[ 0.9602, -0.9900,  0.5403],
        [-0.9111, -0.9900,  0.5403]])
 Tangent tensor([[-0.2910, -0.1425,  1.5574],
        [-0.4523, -0.1425,  1.5574]])
 Sigmoid tensor([[0.9975, 0.9526, 0.7311],
        [0.9999, 0.9526, 0.7311]])
 Softmax tensor([[0.0474, 0.5000, 0.5000],
        [0.9526, 0.5000, 0.5000]])
 Relu tensor([[6., 3., 1.],
        [9., 3., 1.]])


# **Inplace Operations**

In [38]:
m =  torch.rand(2,3)
n =  torch.rand(2,3)
print(m)
print(n)

tensor([[0.1994, 0.5472, 0.0062],
        [0.9516, 0.0753, 0.8860]])
tensor([[0.5832, 0.3376, 0.8090],
        [0.5779, 0.9040, 0.5547]])


In [39]:
m+n

tensor([[0.7826, 0.8848, 0.8151],
        [1.5295, 0.9792, 1.4407]])

In [40]:
m.add_(n)

tensor([[0.7826, 0.8848, 0.8151],
        [1.5295, 0.9792, 1.4407]])

In [41]:
m

tensor([[0.7826, 0.8848, 0.8151],
        [1.5295, 0.9792, 1.4407]])

In [42]:
n

tensor([[0.5832, 0.3376, 0.8090],
        [0.5779, 0.9040, 0.5547]])

In [43]:
torch.relu(m)

tensor([[0.7826, 0.8848, 0.8151],
        [1.5295, 0.9792, 1.4407]])

In [44]:
m.relu_()

tensor([[0.7826, 0.8848, 0.8151],
        [1.5295, 0.9792, 1.4407]])

In [45]:
m

tensor([[0.7826, 0.8848, 0.8151],
        [1.5295, 0.9792, 1.4407]])

In [46]:
m.sigmoid_()

tensor([[0.6862, 0.7078, 0.6932],
        [0.8219, 0.7270, 0.8086]])

# **Copying a Tensor**

In [48]:
a = torch.rand(2,3)
a

tensor([[0.2814, 0.7886, 0.5895],
        [0.7539, 0.1952, 0.0050]])

In [49]:
b = a

In [50]:
b

tensor([[0.2814, 0.7886, 0.5895],
        [0.7539, 0.1952, 0.0050]])

In [58]:
a[0][0]=0

In [59]:
a

tensor([[0.0000, 0.7886, 0.5895],
        [0.7539, 0.1952, 0.0050]])

In [60]:
b

tensor([[0.0000, 0.7886, 0.5895],
        [0.7539, 0.1952, 0.0050]])

In [61]:
id(a)

131939590448192

In [62]:
id(b)

131939590448192

In [63]:
b = a.clone()

In [64]:
a

tensor([[0.0000, 0.7886, 0.5895],
        [0.7539, 0.1952, 0.0050]])

In [65]:
a[0][0]=1.875

In [66]:
a

tensor([[1.8750, 0.7886, 0.5895],
        [0.7539, 0.1952, 0.0050]])

In [67]:
b

tensor([[0.0000, 0.7886, 0.5895],
        [0.7539, 0.1952, 0.0050]])

In [68]:
id(a)

131939590448192

In [69]:
id(b)

131938821742880

## **Tensor Operations on GPU**